version: 2.1

jobs:
  build:
    working_directory: ~/repo/python_app/
    docker: 
      - image: cimg/python:3.7
    steps:
      - checkout

      #- restore_cache:
       #   keys:
        #  - deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: 
          name: Print working directory
          command: pwd
      - run:
          name: list file
          command: ls
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install Flask
            pip3 install coverage
            pip3 install pylint
            python3 -m pip install --upgrade pip
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python3 /repo/python_app/test.py
      - run:
          name: Create report
          command: |
            python3 -m coverage run test.py
            python3 -m coverage report test.py
      - run: 
          name: Run Linter
          command: python3 -m pylint calculator.py


workflows:
  build-test:
    jobs:
      - build